backend:
  name: github
  repo: YOUR-USERNAME/YOUR-REPO   # yahan apna GitHub username/repo-name likhna hai
  branch: main                    # agar branch master hai to master likh dena

media_folder: "static/uploads"    
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
